apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-survey-sdk
  namespace: customer-survey-prod
  labels:
    app: customer-survey
    component: sdk
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer-survey
      component: sdk
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: customer-survey
        component: sdk
        env: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: sdk
          image: ghcr.io/customer-survey-org/customer-survey-sdk:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: github-registry
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - customer-survey
                - key: component
                  operator: In
                  values:
                  - sdk
              topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Service
metadata:
  name: customer-survey-sdk
  namespace: customer-survey-prod
  labels:
    app: customer-survey
    component: sdk
    env: production
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: customer-survey
    component: sdk

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdk-nginx-config
  namespace: customer-survey-prod
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location /docs {
        root /usr/share/nginx/html;
        index index.html;
      }
      
      location /sdk {
        alias /usr/share/nginx/sdk;
        autoindex on;
      }
      
      location /health {
        return 200 '{"status":"UP","service":"sdk-docs","environment":"production"}';
        add_header Content-Type application/json;
      }
    }

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customer-survey-sdk-hpa
  namespace: customer-survey-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-survey-sdk
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 