version: '3.8'

services:
  # MCP Server Integration
  mcp-konnect:
    image: kong/mcp-konnect:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config/mcp-konnect:/etc/mcp-konnect
    environment:
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8000

  mcp-rest-api:
    build:
      context: ./services/mcp-rest-api
    ports:
      - "8001:8001"
    depends_on:
      - mcp-konnect
    environment:
      - MCP_KONNECT_URL=http://mcp-konnect:8000

  # AI Task Management
  claude-task-master:
    build:
      context: ./services/claude-task-master
    ports:
      - "8002:8002"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Web UI Dashboard
  dashboard:
    build:
      context: ./services/dashboard
    ports:
      - "3000:3000"
    depends_on:
      - mcp-konnect
      - mcp-rest-api
      - claude-task-master
      - scraper
      - browser-tools
      - debug-visualizer
    environment:
      - CLAUDE_TASK_MASTER_URL=http://claude-task-master:8002
      - SCRAPER_URL=http://scraper:8003
      - BROWSER_TOOLS_URL=http://browser-tools:8004
      - DEBUG_VISUALIZER_URL=http://debug-visualizer:8005

  # Scraping and Stealth
  scraper:
    build:
      context: ./services/scraper
    ports:
      - "8003:8003"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Browser Monitoring
  browser-tools:
    build:
      context: ./services/browser-tools
    ports:
      - "8004:8004"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Debug Visualizer
  debug-visualizer:
    build:
      context: ./services/debug-visualizer
    ports:
      - "8005:8005"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Dependency Management
  renovate:
    image: renovate/renovate:latest
    volumes:
      - ./config/renovate:/usr/src/app/config
      - /var/run/docker.sock:/var/run/docker.sock 