services:
  # MCP Server Integration
  mcp-konnect:
    image: kong/mcp-konnect:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config/mcp-konnect:/etc/mcp-konnect
    environment:
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8000

  mcp-rest-api:
    image: ${DOCKER_USERNAME}/cursor-devdock-mcp-rest-api:latest
    ports:
      - "8001:8001"
    depends_on:
      - mcp-konnect
    environment:
      - MCP_KONNECT_URL=http://mcp-konnect:8000

  # AI Task Management
  claude-task-master:
    image: ${DOCKER_USERNAME}/cursor-devdock-claude-task-master:latest
    ports:
      - "8002:8002"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Web UI Dashboard
  dashboard:
    image: ${DOCKER_USERNAME}/cursor-devdock-dashboard:latest
    ports:
      - "3000:3000"
    depends_on:
      - mcp-konnect
      - mcp-rest-api
      - claude-task-master
      - scraper
      - browser-tools
      - debug-visualizer
    environment:
      - CLAUDE_TASK_MASTER_URL=http://claude-task-master:8002
      - SCRAPER_URL=http://scraper:8003
      - BROWSER_TOOLS_URL=http://browser-tools:8004
      - DEBUG_VISUALIZER_URL=http://debug-visualizer:8005

  # Scraping and Stealth
  scraper:
    image: ${DOCKER_USERNAME}/cursor-devdock-scraper:latest
    ports:
      - "8003:8003"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Browser Monitoring
  browser-tools:
    image: ${DOCKER_USERNAME}/cursor-devdock-browser-tools:latest
    ports:
      - "8004:8004"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Debug Visualizer
  debug-visualizer:
    image: ${DOCKER_USERNAME}/cursor-devdock-debug-visualizer:latest
    ports:
      - "8005:8005"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Dependency Management
  renovate:
    image: renovate/renovate:latest
    volumes:
      - ./config/renovate:/usr/src/app/config
      - /var/run/docker.sock:/var/run/docker.sock 