services:
  # MCP Server Integration - using mock service
  mcp-konnect:
    build:
      context: ./services/kaneo
      dockerfile: Dockerfile
    ports:
      - "10000:3333"
    volumes:
      - ./config/mcp-konnect:/etc/mcp-konnect
    environment:
      - PORT=3333
    # This is now using our mock service

  mcp-rest-api:
    build:
      context: ./services/mcp-rest-api
    ports:
      - "10001:8001"
    depends_on:
      - mcp-konnect
    environment:
      - MCP_KONNECT_URL=http://mcp-konnect:3333

  # AI Task Management
  claude-task-master:
    build:
      context: ./services/claude-task-master
    ports:
      - "10002:8002"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Web UI Dashboard
  dashboard:
    build:
      context: ./services/dashboard
    ports:
      - "10003:3000"
    depends_on:
      - mcp-konnect
      - mcp-rest-api
      - claude-task-master
      - scraper
      - browser-tools
      - debug-visualizer
      - kaneo
      - nodejs-debugger
      - renovate
    environment:
      - MCP_KONNECT_URL=http://mcp-konnect:3333
      - CLAUDE_TASK_MASTER_URL=http://claude-task-master:8002
      - SCRAPER_URL=http://scraper:8003
      - BROWSER_TOOLS_URL=http://browser-tools:8004
      - DEBUG_VISUALIZER_URL=http://debug-visualizer:8005
      - NODEJS_DEBUGGER_URL=http://nodejs-debugger:8005
      - KANEO_URL=http://kaneo:3333
      - MCP_REST_API_URL=http://mcp-rest-api:8001
      - RENOVATE_SERVICE_URL=http://renovate:8099

  # Scraping and Stealth
  scraper:
    build:
      context: ./services/scraper
    ports:
      - "10004:8003"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Browser Monitoring
  browser-tools:
    build:
      context: ./services/browser-tools
    ports:
      - "10005:8004"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Debug Visualizer
  debug-visualizer:
    build:
      context: ./services/debug-visualizer
    ports:
      - "10006:8005"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Node.js Debugger
  nodejs-debugger:
    build:
      context: ./services/nodejs-debugger
    ports:
      - "10008:12345"
      - "9229:9229"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001
      - PORT=12345

  # Kaneo Dashboard
  kaneo:
    build:
      context: ./services/kaneo
    ports:
      - "10007:3333"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001

  # Dependency Management with custom Renovate service
  renovate:
    build:
      context: ./services/renovate
    ports:
      - "10009:8099"
    environment:
      - MCP_REST_API_URL=http://mcp-rest-api:8001
    volumes:
      - ./:/app/repo 